
function levelName(l){const names={en:{A1:'Foundation',A2:'Everyday',B1:'Independent',B2:'Upper Intermediate',C1:'Advanced'},pt:{A1:'Fundamentos',A2:'Cotidiano',B1:'Independente',B2:'Intermediário avançado',C1:'Avançado'},ro:{A1:'Fundamente',A2:'Viața de zi cu zi',B1:'Independent',B2:'Intermediar superior',C1:'Avansat'}};return names[lang]?.[l]||LEVELS[l].name}
function renderExplain(){activeView='explain';activeView='explain';$('#app').innerHTML=nav()+`<main class="appview"><div class="section-head"><div><div class="eyebrow">${tx('explain')}</div><h2>${tx('explanationTitle')}</h2><p>${tx('explanationIntro')}</p></div></div><div class="explain-grid">${explanations.map(x=>{const def=x.definition[lang]||x.definition.en;const title=x.title_en;const titleTr=lang==='pt'?x.title_pt:lang==='ro'?x.title_ro:x.title_en;return `<article class="explain-card"><div class="chip">${x.level} · ${esc(x.category)}</div><h3>${esc(title)}</h3><div class="translation">${esc(titleTr)}</div><p><strong>${lang.toUpperCase()}:</strong> ${esc(def)}</p><div class="example"><strong>${tx('example')}</strong><br>${x.examples.map(esc).join('<br>')}</div></article>`}).join('')}</div></main>`}
function drawDict(){const q=($('#dictSearch')?.value||'').toLowerCase();const arr=tri.filter(x=>`${x.english} ${x.portuguese} ${x.romanian}`.toLowerCase().includes(q)).slice(0,160);$('#dictCards').innerHTML=arr.map(x=>`<article class="dict-card"><div class="chip">${esc(x.level)}</div><h3>${esc(x.english)}</h3><p><strong>PT:</strong> ${esc(x.portuguese)}</p><p><strong>RO:</strong> ${esc(x.romanian==='—'?(lang==='pt'?'Tradução a revisar pelo professor.':lang==='ro'?'Traducere de revizuit de profesor.':'Translation to be reviewed by teacher.'):x.romanian)}</p><small>${esc(x.type)} · ${esc(x.topic)}</small></article>`).join('')||`<div class="card">${tx('noResults')}</div>`}
function renderTeacher(){activeView='teacher';activeView='teacher';if(!me||me.role!=='teacher'){openLogin(lang==='pt'?'É necessário acesso de professor.':lang==='ro'?'Este necesar accesul profesorului.':'Teacher access required.');return}fetch('/api/teacher/overview').then(r=>r.json()).then(d=>{const students=d.students||[];$('#app').innerHTML=nav()+`<main class="appview"><section class="teacher"><div class="eyebrow" style="color:var(--yellow)">${tx('teacher')}</div><h2 style="font-family:Nunito;font-size:42px">${tx('teacherTitle')}</h2><p style="color:#c9ddd6">${tx('teacherIntro')}</p><div class="statgrid"><div class="stat"><b>${students.length}</b><span>${tx('students')}</span></div><div class="stat"><b>${students.reduce((a,s)=>a+s.tests,0)}</b><span>${tx('completed')}</span></div><div class="stat"><b>${students.length?Math.round(students.reduce((a,s)=>a+s.average,0)/students.length):0}%</b><span>${tx('average')}</span></div><div class="stat"><b>2,550</b><span>${tx('bank')}</span></div></div><div id="studentList">${students.map(s=>`<div class="studentrow"><strong>${esc(s.name)}</strong><span>${esc(s.email)}</span><span>${s.tests} ${lang==='pt'?'testes':lang==='ro'?'teste':'tests'}</span><span>${s.average}% ${lang==='pt'?'média':lang==='ro'?'medie':'avg.'}</span><button class="btn btn-yellow" onclick="studentDetail(${s.id})">${tx('openDiagnosis')}</button></div>`).join('')||`<div class="empty">${lang==='pt'?'Nenhum aluno ainda.':lang==='ro'?'Niciun elev încă.':'No students yet.'}</div>`}</div><div id="detail"></div></section></main>`})}
async function studentDetail(id){const d=await fetch('/api/teacher/student?id='+id).then(r=>r.json());const diag=d.diagnosis||[];$('#detail').innerHTML=`<div style="margin-top:28px"><div class="section-head"><div><h2 style="color:#fff;font-family:Nunito">${esc(d.student.name)}</h2><p style="color:#c9ddd6">${tx('personal')}</p></div></div><div class="diagnosis">${diag.slice(0,12).map(x=>`<div class="diag"><b>${esc(x.skill)}</b><div style="color:var(--yellow);font-family:Nunito;font-size:25px;margin-top:5px">${x.count} ${tx('errors')}</div><small style="color:#bcd4ca">${esc(x.topic)}</small><div class="recommend">${esc(x.recommendation)}</div></div>`).join('')||`<div class="diag">${tx('noMistakes')}</div>`}</div></div>`}
const _oldHome=renderHome; const _oldLearn=renderLearn; const _oldTests=renderTests;
const _oldBoot=boot;
setTimeout(()=>{route(activeView,currentLevel)},0);
